### ISSUE TITLE
Make fetching of relationship's data optional and allow full resource information

### ISSUE THREAD

**Issue by nohponex** [phramework/jsonapi#6]
Also we should be able to include additional metadata besides id.
In order to do that we will have to change the definition (return) of **`getRelationshipBy`** methods. (code breaking change)

``` php
/**
 * @param string categoryId
 * @return RelationshipResource[]
 */
public static function getRelationshipByCategory($categoryId)
{
    //...
}
```

We will introduce a new class 'RelationshipResource`

``` php
class RelationshipResource extends Resource
{
}
```

And we will update the definition of `Resource` class

| Resource |
| --- |
| type |
| id |
| _links_ |
| _attributes_ |
| _relationships_ |
| _meta_ |

A sample response to a GET request will be:

``` json
{
"data": {
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "/articles/1/relationships/author",
        "related": "/articles/1/author"
      },
      "data": {
        "type": "people",
        "id": "9",
        "attributes": {
          "name": "My Name"
        },
        "meta": {
           "count" : 10
         }
       }
    }
  }
}
}
```

See work in progress:
[full-jsonapi-resource.txt](https://github.com/phramework/jsonapi/files/114195/full-jsonapi-resource.txt)
- [x] Write helper class for `Resource` and `RelationshipResource` https://github.com/phramework/jsonapi/issues/8
- [x] Minimize relationship and resource related code in `Model` class
- [x] Support fields directive for relationship resources
- [x] Parse as resource available resource's relationship data as relationship resource
- [x] Should we add relationship data callbacks for `TYPE_TO_ONE` items ?
- [x] Allow return of both string[] and RelationshipResource[] from relationship data callbacks
- [ ] Make use of `Resource::PARSE_RELATIONSHIP_ATTRIBUTES`
- [x] Figure out how `meta` can be parsed into a resource
- [x] Don't output unnecessary resource properties
- [x] Research proposed comment https://github.com/phramework/jsonapi/issues/6#issuecomment-178647848 
- [x] Complete test coverage https://github.com/phramework/jsonapi/issues/11
- [ ] Full controller support over relationships

**Comment by nohponex** [comment]
Also we **MAY** change the definition of `getRelationshipBy` methods to use relationship's key instead of resource type. 
or a concatenation of type and relationship key

**Comment by alkallio** [comment]
> or a concatenation of type and relationship key

Concatenate only if type is different from the relationship key.

**Comment by nohponex** [comment]
Also note links can have meta too see [jsonapi](http://jsonapi.org/format/#document-links)
